### ISSUE TITLE
Kitsu tracking is not working.

### ISSUE THREAD

**Issue by evansh28** [aniyomiorg/aniyomi-extensions#2770]
### Source information

Kitsu

### Source language

English

### Steps to reproduce

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi-extensions/files/13963195/aniyomi_crash_logs.txt)

First I added one manga in library
Second I select Kitsu for tracking
Third I received crash which is given into text file.

### Expected behavior

This should be shown list

### Actual behavior

This is showing crash log with error.

### Aniyomi version

0.15.2.1

### Android version

Android 11

### Other details

I can't add new tracking in kitsu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.
