### ISSUE TITLE
Add Jellyfin progress tracker

### ISSUE THREAD

**Issue by sam5558** [aniyomiorg/aniyomi-extensions#2802]
### Source name

Jellyfin

### Source language

All

### Describe your suggested feature

First of all i would like to thank the developer(s) of this project for his/her/their awesome work.

It would be really useful if we could get a both-way synchronization between Jellyfin (Server) and Jellyfin extension (Aniyomi).
Having it available in the tracking section would avoid having to manually maintain progress twice in Aniyomi & Jellyfin server.

As an instance, i know that this tracking is available in tachiyomi that is able to provide a tracking with self-hosted solutions like komga and kavita, which can be an inspiration for a similar approach for Jellyfin tracking.

Regards

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
>If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).

Enhanced trackers are part of the main app, not an extension. Will be solved by [#1341](https://github.com/aniyomiorg/aniyomi/pull/1341)
