### ISSUE TITLE
Issue Template outdated | Aniyomi 0.15.2.4

### ISSUE THREAD

**Issue by LittleFreak** [aniyomiorg/aniyomi-extensions#2906]
### Describe why this should be added

Your Github-Template for Bugs is still asking to update to the "latest" stable version `0.12.x.x`, when it should be `0.15.2.4`

### Other details

https://github.com/aniyomiorg/aniyomi/releases

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [ ] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
I guess the same applies to the 'Meta'-Template

**Comment by Claudemirovsky** [comment]
forgot to close in #2933 lol
